packages:
  - '.'
minimumReleaseAgeExclude:
  - mastra
  - "@mastra/*"
allowBuilds:
  bufferutil: true
  esbuild: true
  onnxruntime-node: false
  protobufjs: true
  sharp: true
  utf-8-validate: true
